---
apiVersion: v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: kuttl
rules:
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - get
  - list  
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - services
  - pods
  - secrets
  - clowdenvironments
  - clowdapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "cloud.redhat.com"
  resources:
  - clowdenvironments
  - clowdapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuttl
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kuttl
subjects:
- kind: User
  name: system:serviceaccount:buddy:kuttl
roleRef:
  kind: ClusterRole
  name: kuttl
  apiGroup: rbac.authorization.k8s.io
